In [1]:
# buatlah 2 buah matrix
matrix1 = [[24,12,7],[15,13,17],[3,5,9]]
matrix2 = [[8,10,30],[12,7,9],[10,5,27]]

import numpy as np
#soal 1 2(a*b)
matrixA = np.array(matrix1)
matrixB = np.array(matrix2)
soal1 = 2* np.dot(matrixA, matrixB)
print(soal1)

#soal 2 A*(invers dari (A+B)
soal2 = np.dot(matrixA, np.linalg.inv(matrixA+matrixB))
print(soal2)

[[ 812  718 2034]
 [ 892  652 2052]
 [ 348  220  756]]
[[ 3.06654991 -2.0262697  -1.4938704 ]
 [-1.0262697   1.58931699  0.37915937]
 [-1.48861646  1.56129597  0.65236427]]
